version: "3"
services:
  jenkins:
    build: "./jenkins"
    container_name: "workshop-jenkins"
    environment: 
      JAVA_OPTS: "-Djava.awt.headless=true -Duser.timezone=Asia/Tokyo -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8"
    ports:
      - "18080:8080"
      - "50000:50000"
    volumes:
      - "vol-jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
  sonar:
    image: "sonarqube:lts"
    container_name: "workshop-sonar"
    ports:
      - "9000:9000"
  mariadb:
    build: "./mariadb"
    container_name: "workshop-mariadb"
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: backlog
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: backlog

volumes:
  vol-jenkins: