version: "2"
services:
  jenkins:
    build: "./jenkins"
    container_name: "workshop-jenkins"
    environment: 
      JAVA_OPTS: "-Djava.awt.headless=true -Duser.timezone=Asia/Tokyo -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8"
    ports:
      - "1080:8080"
    volumes:
      - "vol-nginx:/usr/share/nginx/html"
      - "vol-jenkins:/var/jenkins_home"
  sonar:
    image: "sonarqube:lts"
    container_name: "workshop-sonar"
    ports:
      - "9000:9000"
  nginx:
    build: "./nginx"
    container_name: "workshop-nginx"
    ports:
      - "80:80"
    volumes:
      - "vol-nginx:/usr/share/nginx/html"
  mariadb:
    build: "./mariadb"
    container_name: "workshop-mariadb"
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: backlog
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: backlog

volumes:
  vol-jenkins:
  vol-nginx: